// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkandfizerwyimccwrov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprYW5kZml6ZXJ3eWltY2N3cm92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk2MDIwNjAsImV4cCI6MjA4NTE3ODA2MH0.lllYRiYnHzsUCMTeXrhPSh1A9W8i1oFYMfEF34VTQHY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});